### PR TITLE
Add pending tests count to the stats section

### PR DESCRIPTION
**Pull request by zend**
The pending(skipped) tests count is missing in the stats section, it will cause some tricky problems.

Add `output.stats.pendings`

### CODE REVIEW

**Comment by randing89** [comment]
Thanks

**Comment by zend** [comment]
@randing89 Hi Ran, could you please publish a new release on the npm repo?

**Comment by randing89** [comment]
Hey thanks for reaching out. I just realized I don’t actually own the NPM package. Someone owns it and they were gone. I will publish this package again under a different name. Thanks.Regards,RanOn Sep 15, 2022, at 11:24, Zenghai Liang ***@***.***> wrote:﻿
@randing89 Hi Ran, could you please publish a new release on the npm repo?

**Comment by randing89** [comment]
Here you go https://www.npmjs.com/package/jest-bamboo-reporter2

**Pull request merged**
